apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: stockticker

commonLabels:
  app: stockticker

secretGenerator:
- name: stockticker-apikey
  files:
  - apikey.txt

resources:
- deployment.yaml
- service.yaml
- configMap.yaml
